# Generated by Django 3.1.7 on 2022-02-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bannerinfo_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='send_type',
            field=models.IntegerField(choices=[(1, 'register'), (2, 'forget'), (3, 'change')], default=1, verbose_name='验证码类型'),
        ),
    ]
