# Generated by Django 3.1.7 on 2022-02-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orginfo',
            options={'ordering': ['id'], 'verbose_name': '机构信息', 'verbose_name_plural': '机构信息'},
        ),
    ]
