# Generated by Django 3.1.7 on 2022-02-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='category',
            field=models.CharField(choices=[('qd', '前端'), ('hd', '后端'), ('ai', '人工智能')], max_length=5, verbose_name='课程类型'),
        ),
    ]
